# Generated by Django 3.2.6 on 2021-08-29 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approved_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='approval',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='application', to='leave.application'),
        ),
    ]
