# Generated by Django 3.2.6 on 2021-08-29 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_auto_20210829_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
