# Generated by Django 3.2.6 on 2021-08-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210829_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='application', to='leave.application'),
        ),
    ]
