# Generated by Django 3.2.6 on 2021-08-29 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0004_alter_approval_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approved_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
