# Generated by Django 3.2.6 on 2021-10-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20210920_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='application',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approved_on',
        ),
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
