# Generated by Django 3.2.6 on 2021-11-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0009_auto_20211024_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Till')),
                ('reason', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leave_form', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leave.leavetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='approval',
            name='created',
            field=models.DateField(default=leave.models.get_local_time, editable=False),
        ),
        migrations.AddField(
            model_name='approval',
            name='modified',
            field=models.DateTimeField(default=leave.models.get_local_time),
        ),
        migrations.AddField(
            model_name='approval',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='leave_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leaveform'),
        ),
    ]
