# Generated by Django 3.2.6 on 2021-11-07 06:48

from django.db import migrations, models
import django.db.models.deletion
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20211103_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='leave_form',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leave_form', to='leave.approval'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='created',
            field=models.DateTimeField(default=leave.models.get_local_time, editable=False),
        ),
    ]
