# Generated by Django 3.2.6 on 2021-08-10 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('token', models.CharField(max_length=64, null=True)),
                ('team_id', models.CharField(max_length=32, null=True)),
                ('team_domain', models.CharField(max_length=64, null=True)),
                ('channel_id', models.CharField(max_length=64, null=True)),
                ('channel_name', models.CharField(max_length=32, null=True)),
                ('user_id', models.CharField(max_length=64, null=True)),
                ('user_name', models.CharField(max_length=64, null=True)),
                ('command', models.CharField(max_length=32, null=True)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('api_app_id', models.CharField(max_length=64, null=True)),
                ('is_enterprise_install', models.BooleanField(default=False)),
                ('response_url', models.URLField(null=True)),
                ('trigger_id', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_out', to='attendance.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='attendance.timesheet')),
            ],
        ),
    ]
