# Generated by Django 3.2.6 on 2021-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackpayload',
            name='text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
