# Generated by Django 3.2.6 on 2021-08-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_slackpayload_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackpayload',
            name='api_app_id',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='channel_id',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='channel_name',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='command',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='is_enterprise_install',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='response_url',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='team_domain',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='team_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='text',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='token',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='trigger_id',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='user_id',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='slackpayload',
            name='user_name',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
