# Generated by Django 3.2.6 on 2021-10-01 18:00

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20210927_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.TimeField(default=attendance.models.getLocalTime),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='time',
            field=models.TimeField(default=attendance.models.getLocalTime),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='response_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
