# Generated by Django 3.2.6 on 2021-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_checkin_checkout_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='time',
            field=models.TimeField(auto_created=True),
        ),
    ]
