# Generated by Django 3.2.6 on 2021-10-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20211002_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
