# Generated by Django 3.2.6 on 2021-10-03 13:35

import attendance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0007_alter_timesheet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slackuser',
            name='slack_user',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='name',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(default=attendance.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
