# Generated by Django 3.2.6 on 2021-10-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20211021_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='day_of_the_week',
            field=models.PositiveIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, verbose_name='Day of the week'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='work_days',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
