# Generated by Django 3.2.6 on 2021-10-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20211024_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['id']},
        ),
    ]
